name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          config-file: .release-please-config.json
          # NOTE: Org setting blocks PRs by Actions. Enable it, or set the next line to 'true' to bypass PR creation.
          skip-github-pull-request: false
