name: Sync Events (daily)

on:
  schedule:
    # 03:00 JST daily (18:00 UTC previous day)
    - cron: '0 18 * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Check DATABASE_URL is set
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL is NOT set in Secrets" >&2
            exit 1
          else
            echo "DATABASE_URL is set (value hidden)"
          fi
      - name: Migrate schema (deploy)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Run sync script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          node scripts/sync-events.js || echo "No sources or sync failed; see logs"
